// mockDataLiquidacion.ts

export const cabecera = {
  id: 101,
  nombre_personal_operador: "Juan Pérez",
  nombre_division_negocio: "Transporte Nacional",
  fecha_liquidacion: "2025-07-16",
  nombre_status: "Aprobado",
  monto_gastos_viaje: 1500.00,
  monto_deduccion: 300.00,
  monto_percepcion: 800.00,
  monto_obligacion: 100.00,
  monto_total_pagar: 1900.00,
};

export const conceptos = [
  {
    id: 1,
    nombre_concepto: "Combustible",
    observaciones: "Reembolso",
    nombre_viaje: "Viaje A",
    cantidad: 1,
    subtotal: 1000,
    iva: 160,
    retencion: 50,
    total: 1110,
  },
  {
    id: 2,
    nombre_concepto: "Caseta",
    observaciones: "",
    nombre_viaje: "Viaje B",
    cantidad: 3,
    subtotal: 300,
    iva: 48,
    retencion: 0,
    total: 348,
  },
];

export const viajesAsociados = [
  {
    id: 1,
    nombre_viaje: "Viaje A",
    nombre_unidad: "Unidad 101",
    nombre_remolque1: "Remolque R1",
    nombre_dolly: "Dolly D1",
    nombre_remolque2: "Remolque R2",
    nombre_configuracion_armado: "Completa",
    nombre_usuario_registro: "admin",
    sueldo_operador: 500,
    fecha_inicial: "2025-07-01",
    fecha_final: "2025-07-05",
    kilometraje_inicial: 10000,
    kilometraje_final: 10250,
    kilometraje_recorrido: 250,
    estado_carga: "Cargado",
    litros_combustible: 200,
    fecha_registro: "2025-07-06",
  },
  {
    id: 2,
    nombre_viaje: "Viaje B",
    nombre_unidad: "Unidad 102",
    nombre_remolque1: "Remolque R3",
    nombre_dolly: "Dolly D2",
    nombre_remolque2: "Remolque R4",
    nombre_configuracion_armado: "Sencilla",
    nombre_usuario_registro: "jlopez",
    sueldo_operador: 600,
    fecha_inicial: "2025-07-08",
    fecha_final: "2025-07-10",
    kilometraje_inicial: 10500,
    kilometraje_final: 10700,
    kilometraje_recorrido: 200,
    estado_carga: "Vacío",
    litros_combustible: 180,
    fecha_registro: "2025-07-11",
  },
];
