// data.ts

export const empresaList = {
  "razon_social": "Transportes del Norte S.A. de C.V.",
  "rfc": "TND123456789",
  "direccion":
    "Avenida de los Insurgentes Sur 1234, Col. Del Valle, CDMX, México",
};

export const pedidoList = {
        "id": 2,
        "fecha_solicitud": "2025-06-02",
        "fk_cliente_id": 189,
        "nombre_cliente": "CL-0187 - RAYMUNDO AMADOR GARABITO",
        "rfc_cliente": "AAGR9405163E9",
        "fk_cliente_remitente_id": 2,
        "nombre_cliente_remitente": "CL-0002 - AGRICOLA GOVA",
        "fk_cliente_remitente_ubicacion_id": 5,
        "nombre_cliente_remitente_ubicacion": "Interamericana de Negocios",
        "fk_cliente_remitente_direccion_id": 10,
        "nombre_cliente_remitente_direccion": "RIO PANUCO 80, Las Ceibas/Lagos de Moreno, Lagos de Moreno, 47440, México, Fiscal",
        "fk_cliente_destinatario_id": 1,
        "nombre_cliente_destinatario": "CL-0001 - ABSORMEX CMPC TISSUE",
        "fk_cliente_destinatario_ubicacion_id": 1,
        "nombre_cliente_destinatario_ubicacion": "Auto Transportes Cisneros Sabinas",
        "fk_cliente_destinatario_direccion_id": 1,
        "nombre_cliente_destinatario_direccion": "AVENIDA INDUSTRIAL HUMBERTO LOBO 9013 9013, Ciudad Industrial Mitras/García, García, 66023, México, Fiscal",
        "fk_ruta_id": 0,
        "nombre_ruta": "",
        "fk_division_negocio_id": 2,
        "nombre_division_negocio": "Caja Seca",
        "fk_configuracion_armado_id": 2,
        "nombre_configuracion_armado": "Sencillo",
        "fk_clf_tipo_operacion_id": 7,
        "nombre_clf_tipo_operacion": "Nacional",
        "fk_clf_tipo_temperatura_id": 13,
        "nombre_clf_tipo_temperatura": "°C",
        "temperatura_producto": 0,
        "referencia": "",
        "fk_moneda_id": 1,
        "nombre_moneda": "Peso mexicano",
        "fk_tasa_iva_id": 3,
        "nombre_tasa_iva": "Tasa 16%",
        "factor_tasa_iva": 0.160000,
        "fk_forma_pago_id": 29,
        "nombre_forma_pago": "99 - Por definir",
        "fk_metodo_pago_id": 3,
        "nombre_metodo_pago": "PPD - Pago en parcialidades o diferido",
        "fk_uso_cfdi_id": 13,
        "nombre_uso_cfdi": "G03 - Gastos en general",
        "fecha_carga": "2025-06-02 09:00:00",
        "fecha_descarga": "2025-06-02 09:00:00",
        "observaciones": "",
        "fk_clf_forma_valoracion_id": 15,
        "nombre_clf_forma_valoracion": "MANUAL",
        "subtotal": 39503.00,
        "iva": 6320.48,
        "retencion": 1580.00,
        "total": 44243.48,
        "fk_status_id": 5,
        "nombre_status": "Cancelado",
        "fk_remision_id": 1,
        "folio_remision": "CCPE-15793",
        "fk_empresa_id": 1,
        "nombre_empresa": "Cisneros"
    }

export const mercanciasList = [
  {
            "id": 3,
            "fk_mercancia_id": 1,
            "clave": "14121500",
            "nombre_mercancia": "14121500 - Rollos de Papel",
            "clave_alterna": "",
            "cantidad": 1.00,
            "piezas": 1.00,
            "fk_clave_unidad_id": 4,
            "clave_unidad": "10 - Grupos",
            "fk_embalaje_id": 1,
            "nombre_embalaje": "1A1 - Bidones (Tambores) de Acero 1 de tapa no desmontable",
            "fk_clave_producto_servicio_id": 43346,
            "nombre_clave_producto_servicio": "50466701 - +æame agria africana enlatada o envasada",
            "peso": 1.00,
            "peso_kgs": 10.00,
            "fk_unidad_peso_id": 212,
            "nombre_unidad_peso": "A75 - Tonelada de carga",
            "material_peligroso": true,
            "fk_clave_material_peligroso_id": 50,
            "nombre_clave_material_peligroso": "0084 - EXPLOSIVOS PARA VOLADURAS, TIPO D?",
            "fk_fraccion_id": 1,
            "nombre_fraccion": "001 - CC-PRODUCTOS ALIMENTICIOS",
            "fk_fraccion_arancelaria_id": 2,
            "nombre_fraccion_arancelaria": "01012901 - Para saltos o carreras.",
            "fk_tipo_material_id": 3,
            "nombre_tipo_material": "03 - Materia terminada (producto terminado)",
            "observaciones": "",
            "fecha_registro": "02/06/2025",
            "nombre_usuario_registro": "Eva Admin Prod"
        }
];
export const serviciosList = [
  {
                "id": 5,
                "fk_servicio_id": 1,
                "nombre_servicio": "Servicio de Flete",
                "cantidad": 1.00,
                "subtotal": 39500.00,
                "iva": 6320.00,
                "retencion": 1580.00,
                "total": 44240.00,
                "fk_clave_producto_servicio_id": 48777,
                "nombre_clave_producto_servicio": "Transporte de carga por carretera",
                "fk_clave_unidad_id": 678,
                "nombre_clave_unidad": "Unidad de servicio",
                "fk_tasa_iva_id": 3,
                "nombre_tasa_iva": "Tasa 16%",
                "factor_tasa_iva": 0.160000,
                "fk_retencion_iva_id": 7,
                "nombre_retencion_iva": "Retencion del 4%",
                "factor_retencion_iva": 0.040000,
                "fk_retencion_isr_id": 0,
                "nombre_retencion_isr": "",
                "factor_retencion_isr": 0.000000,
                "ieps_check": false,
                "ieps": 0.000000,
                "observaciones": "",
                "fecha_registro": "02/06/2025",
                "nombre_usuario_registro": "Eva Admin Prod"
            },
            {
                "id": 6,
                "fk_servicio_id": 2,
                "nombre_servicio": "Maniobra",
                "cantidad": 1.00,
                "subtotal": 1.00,
                "iva": 0.16,
                "retencion": 0.00,
                "total": 1.16,
                "fk_clave_producto_servicio_id": 48798,
                "nombre_clave_producto_servicio": "Carga y descarga de mercancías",
                "fk_clave_unidad_id": 678,
                "nombre_clave_unidad": "Unidad de servicio",
                "fk_tasa_iva_id": 3,
                "nombre_tasa_iva": "Tasa 16%",
                "factor_tasa_iva": 0.160000,
                "fk_retencion_iva_id": 0,
                "nombre_retencion_iva": "",
                "factor_retencion_iva": 0.000000,
                "fk_retencion_isr_id": 0,
                "nombre_retencion_isr": "",
                "factor_retencion_isr": 0.000000,
                "ieps_check": false,
                "ieps": 0.000000,
                "observaciones": "",
                "fecha_registro": "02/06/2025",
                "nombre_usuario_registro": "Eva Admin Prod"
            },
            {
                "id": 7,
                "fk_servicio_id": 3,
                "nombre_servicio": "Peaje",
                "cantidad": 1.00,
                "subtotal": 2.00,
                "iva": 0.32,
                "retencion": 0.00,
                "total": 2.32,
                "fk_clave_producto_servicio_id": 48874,
                "nombre_clave_producto_servicio": "Carretera o autopista o autopista de peaje interestatal",
                "fk_clave_unidad_id": 678,
                "nombre_clave_unidad": "Unidad de servicio",
                "fk_tasa_iva_id": 3,
                "nombre_tasa_iva": "Tasa 16%",
                "factor_tasa_iva": 0.160000,
                "fk_retencion_iva_id": 0,
                "nombre_retencion_iva": "",
                "factor_retencion_iva": 0.000000,
                "fk_retencion_isr_id": 0,
                "nombre_retencion_isr": "",
                "factor_retencion_isr": 0.000000,
                "ieps_check": false,
                "ieps": 0.000000,
                "observaciones": "",
                "fecha_registro": "02/06/2025",
                "nombre_usuario_registro": "Eva Admin Prod"
            }
];
