export const conceptos = [
  {
    item: 1,
    concepto: 'Sueldo de Viaje',
    observaciones: 'sin información',
    viaje: 'Ruta 1 - Medellín',
    cantidad: '$ 1.00',
    subtotal: '$ 1,750.00',
    iva: '$ 0.00',
    retencion: '$ 0.00',
    total: '$ 1,750.00',
    acciones: '',
  },
  {
    item: 2,
    concepto: 'Bono nocturno',
    observaciones: 'Aplica por viaje nocturno',
    viaje: 'Ruta 3 - Bucaramanga',
    cantidad: '$ 1.00',
    subtotal: '$ 150.00',
    iva: '$ 0.00',
    retencion: '$ 10.00',
    total: '$ 140.00',
    acciones: '',
  },
  {
    item: 3,
    concepto: 'Viáticos',
    observaciones: 'Alimentación y hospedaje',
    viaje: 'Ruta 5 - Santa Marta',
    cantidad: '$ 1.00',
    subtotal: '$ 320.00',
    iva: '$ 0.00',
    retencion: '$ 0.00',
    total: '$ 320.00',
    acciones: '',
  },
  {
    item: 4,
    concepto: 'Mantenimiento menor',
    observaciones: 'Cambio de llanta',
    viaje: 'Taller Medellín',
    cantidad: '$ 1.00',
    subtotal: '$ 250.00',
    iva: '$ 19.00',
    retencion: '$ 0.00',
    total: '$ 269.00',
    acciones: '',
  },
  {
    item: 5,
    concepto: 'Bonificación',
    observaciones: 'Meta cumplida',
    viaje: 'Ruta 4 - Cali',
    cantidad: '$ 1.00',
    subtotal: '$ 500.00',
    iva: '$ 0.00',
    retencion: '$ 50.00',
    total: '$ 450.00',
    acciones: '',
  },
  {
    item: 6,
    concepto: 'Sueldo base',
    observaciones: 'Nómina mensual',
    viaje: '—',
    cantidad: '$ 1.00',
    subtotal: '$ 2,200.00',
    iva: '$ 0.00',
    retencion: '$ 200.00',
    total: '$ 2,000.00',
    acciones: '',
  },
  {
    item: 7,
    concepto: 'Reembolso peajes',
    observaciones: '4 peajes - recibos anexos',
    viaje: 'Ruta 2 - Barranquilla',
    cantidad: '$ 1.00',
    subtotal: '$ 100.00',
    iva: '$ 0.00',
    retencion: '$ 0.00',
    total: '$ 100.00',
    acciones: '',
  },
  {
    item: 8,
    concepto: 'Anticipo',
    observaciones: 'Autorizado por supervisor',
    viaje: 'Ruta 6 - Cúcuta',
    cantidad: '$ 1.00',
    subtotal: '$ 500.00',
    iva: '$ 0.00',
    retencion: '$ 0.00',
    total: '$ 500.00',
    acciones: '',
  },
  {
    item: 9,
    concepto: 'Rendimiento',
    observaciones: 'Excelente desempeño',
    viaje: '—',
    cantidad: '$ 1.00',
    subtotal: '$ 300.00',
    iva: '$ 0.00',
    retencion: '$ 0.00',
    total: '$ 300.00',
    acciones: '',
  },
  {
    item: 10,
    concepto: 'Multa por retraso',
    observaciones: '2 horas de demora',
    viaje: 'Ruta 9 - Montería',
    cantidad: '$ 1.00',
    subtotal: '$ -100.00',
    iva: '$ 0.00',
    retencion: '$ 0.00',
    total: '$ -100.00',
    acciones: '',
  }
];
